function mscmd_extract_clips(input_path,detect_path,output_clips_path,opts)
%MSCMD_EXTRACT_CLIPS - Extract clips from raw/preprocessed data array
%                      centered at a collection of event times.
%
%This is a wrapper to the command-line call to mountainsort. It has similar
%functionality to ms_extract_clips.
%
% Syntax:  mscmd_extract_clips(input_path,detect_path,output_clips_path,opts)
%
% Inputs:
%    input_path - path to MxN array of raw or pre-processed data
%    detect_path - 2xNC array, for example generated by mscmd_detect, the
%                  second of row of which contains the integer time points
%                  (event times)
%    output_path - output path for the MxTxNC array of extracted clips
%    opts. clip_size - integer, e.g. 100 (timepoints)
%
% Other m-files required: mscmd_exe
%
% See also: ms_extract_clips, mscmd_detect

% Author: Jeremy Magland
% Jan 2016; Last revision: 13-Feb-2016

if (nargin<4) opts=struct; end;

cmd=sprintf('%s extract_clips --input=%s --detect=%s --output_clips=%s --clip_size=%d ',mscmd_exe,input_path,detect_path,output_clips_path,opts.clip_size);

fprintf('\n*** EXTRACT CLIPS ***\n');
fprintf('%s\n',cmd);
status=system(cmd);

if (status~=0)
    error('mountainsort returned with error status %d',status);
end;

end
