function ms_mountainview(view_params)
%MS_MOUNTAINVIEW - Launch the MountainView viewer (needs to be compiled
%separately)
%
%The MountainView program allows interactive visualization of the results
%of a spike sorting run.
%
% Syntax:  ms_mountainview(view_params)
%
% Inputs:
%    (Most are optional)
%    view_params.mode - 'overview' , 'overview2' (default), or 'compare_labels'
%    view_params.raw - MxN raw data (array or path to .mda)
%    view_params.filt - MxN filtered data (array or path to .mda)
%    view_params.pre - MxN preprocessed data (array or path to .mda)
%    view_params.firings - RxL array of times/labels etc. according to
%                           the docs. R is at least 3. The second row is 
%                           the times, the third row is the labels. (array
%                           or path to .mda)
%    view_params.templates - path to MxTxK array of spike type templates
%    view_params.clips - path to MxTxL array of clips prepared by
%                        mscmd_create_clips_index
%    view_params.clips_index - path to vector prepared by mscmd_create_clips_index
%    view_params.cross_correlograms - path to cross-correlogram data generated by
%                                     mscmd_cross_correlograms
%    view_params.sampling_freq - the sampling frequency in Hz
%    view_params.locations - path to Mx2 array of 2D coordinates of electrode
%                            layout (visualization only)
%
% Other m-files required: none
%
% See also: mscmd_create_clips_index, mscmd_cross_correlograms

% Author: Jeremy Magland
% Jan 2015; Last revision: 15-Feb-2106

mfile_path=fileparts(mfilename('fullpath'));
exe_fname=sprintf('%s/../mountainview/bin/mountainview',mfile_path);

cmd='';
cmd=[cmd,sprintf('%s ',exe_fname)];

if ~isfield(view_params,'mode')
    view_params.mode='overview2';
end;

if isfield(view_params,'mode')
    cmd=[cmd,sprintf('--mode=%s ',view_params.mode)];
end;
if isfield(view_params,'raw')
    view_params.raw=create_temporary_path_if_array32(view_params.raw);
    cmd=[cmd,sprintf('--raw=%s ',view_params.raw)];
end;
if isfield(view_params,'filt')
    view_params.filt=create_temporary_path_if_array32(view_params.filt);
    cmd=[cmd,sprintf('--filt=%s ',view_params.filt)];
end;
if isfield(view_params,'pre')
    view_params.pre=create_temporary_path_if_array32(view_params.pre);
    cmd=[cmd,sprintf('--pre=%s ',view_params.pre)];
end;
if isfield(view_params,'clusters') %for historical compatibility
    cmd=[cmd,sprintf('--firings=%s ',view_params.clusters)];
end;
if isfield(view_params,'firings')
    view_params.firings=create_temporary_path_if_array64(view_params.firings);
    cmd=[cmd,sprintf('--firings=%s ',view_params.firings)];
end;
if isfield(view_params,'templates')
    cmd=[cmd,sprintf('--templates=%s ',view_params.templates)];
end;
if isfield(view_params,'data')
    view_params.data=create_temporary_path_if_array(view_params.data);
    cmd=[cmd,sprintf('--data=%s ',view_params.data)];
end;
if isfield(view_params,'labels')
    view_params.labels=create_temporary_path_if_array32(view_params.labels);
    cmd=[cmd,sprintf('--labels=%s ',view_params.labels)];
end;
if (isfield(view_params,'clips'))&&(isfield(view_params,'clips_index'))
    cmd=[cmd,sprintf('--clips=%s ',view_params.clips)];
    cmd=[cmd,sprintf('--clips_index=%s ',view_params.clips_index)];
end;
if isfield(view_params,'cross_correlograms')
    cmd=[cmd,sprintf('--cross_correlograms=%s ',view_params.cross_correlograms)];
end;
if isfield(view_params,'sampling_freq')
    cmd=[cmd,sprintf('--sampling_freq=%f ',view_params.sampling_freq)];
end;
if isfield(view_params,'locations')
    view_params.locations=create_temporary_path_if_array32(view_params.locations);
    cmd=[cmd,sprintf('--locations=%s ',view_params.locations)];
end;

fprintf('%s\n',cmd);
system(sprintf('%s &',cmd));

end

function path=create_temporary_path_if_array32(X)
if (isstr(X)) path=X; return; end;
path=create_temporary_mda_path;
writemda32(X,path);
end

function path=create_temporary_path_if_array64(X)
if (isstr(X)) path=X; return; end;
path=create_temporary_mda_path;
writemda64(X,path);
end

function path=create_temporary_mda_path
path=[tempdir,'/mountainsort'];
if ~exist(path)
    mkdir(path);
end;
path=sprintf('%s/ms_mountainview_tmp_%d_%d.mda',path,randi(1e7),randi(1e7));
end
