function ms_mountainview(view_params)
%MS_MOUNTAINVIEW - Launch the MountainView viewer (needs to be compiled
%separately)
%
%The MountainView program allows interactive visualization of the results
%of a spike sorting run.
%
% Syntax:  ms_mountainview(view_params)
%
% Inputs:
%    (Most are optional)
%    view_params.raw - MxN raw or preprocessed data
%    view_params.clusters - RxL array of times/labels etc. according to
%                           the docs. R is at least 3. The second row is 
%                           the times, the third row is the labels.
%    view_params.templates - MxTxK array of spike type templates
%    view_params.clips - MxTxL array of clips prepared by
%                        mscmd_create_clips_index
%    view_params.clips_index - vector prepared by mscmd_create_clips_index
%    view_params.cross_correlograms - cross-correlogram data generated by
%                                     mscmd_cross_correlograms
%    view_params.locations - Mx2 array of 2D coordinates of electrode
%                            layout (visualization only)
%
% Other m-files required: none
%
% See also: mscmd_create_clips_index, mscmd_cross_correlograms

% Author: Jeremy Magland
% Jan 2015; Last revision: 15-Feb-2106

mfile_path=fileparts(mfilename('fullpath'));
exe_fname=sprintf('%s/../mountainview/bin/mountainview',mfile_path);

cmd='';
cmd=[cmd,sprintf('%s ',exe_fname)];

if isfield(view_params,'raw')
    cmd=[cmd,sprintf('--raw=%s ',view_params.raw)];
end;
if isfield(view_params,'clusters')
    cmd=[cmd,sprintf('--clusters=%s ',view_params.clusters)];
end;
if isfield(view_params,'templates')
    cmd=[cmd,sprintf('--templates=%s ',view_params.templates)];
end;
if (isfield(view_params,'clips'))&&(isfield(view_params,'clips_index'))
    cmd=[cmd,sprintf('--clips=%s ',view_params.clips)];
    cmd=[cmd,sprintf('--clips_index=%s ',view_params.clips_index)];
end;
if isfield(view_params,'cross_correlograms')
    cmd=[cmd,sprintf('--cross_correlograms=%s ',view_params.cross_correlograms)];
end;
if isfield(view_params,'locations')
    cmd=[cmd,sprintf('--locations=%s ',view_params.locations)];
end;

fprintf('%s\n',cmd);
system(sprintf('%s &',cmd));

end
